apiVersion: v2
name: kagenti
description: A Helm chart for deploying the kagenti platform
type: application
version: 0.1.2
appVersion: "0.1.2"

dependencies:
- name: kagenti-operator-chart
  version: 0.2.0-alpha.19  # TODO: Bump after kagenti-operator PR #159 merges (removes AgentBuild CRD)
  repository: oci://ghcr.io/kagenti/kagenti-operator
  condition: components.agentOperator.enabled
- name: kagenti-webhook-chart
  version: 0.4.0-alpha.2
  repository: oci://ghcr.io/kagenti/kagenti-extensions
  condition: components.platformWebhook.enabled
